"""
Czech chart of accounts seed data.
Source: Vyhláška č. 500/2002 Sb. — pro podnikatele (účtující v soustavě PÚ).
DPH rates reflect zákon 235/2004 Sb. as amended (standard 21%, reduced 12%,
second reduced 0% for specific supplies, effective from consolidation 2024).
"""

CHART_OF_ACCOUNTS = [
    # ─────────────────────────────────────────────────────────────
    # CLASS 0 — DLOUHODOBÝ MAJETEK (Fixed Assets)
    # ─────────────────────────────────────────────────────────────
    {"account_number": "01",  "name_cz": "Dlouhodobý nehmotný majetek", "name_en": "Intangible fixed assets", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET", "is_synthetic": False, "allows_posting": False},
    {"account_number": "011", "name_cz": "Zřizovací výdaje", "name_en": "Formation expenses", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "012", "name_cz": "Nehmotné výsledky výzkumu a vývoje", "name_en": "Intangible R&D results", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "013", "name_cz": "Software", "name_en": "Software", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "014", "name_cz": "Ocenitelná práva", "name_en": "Valuable rights", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "015", "name_cz": "Goodwill", "name_en": "Goodwill", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "019", "name_cz": "Jiný dlouhodobý nehmotný majetek", "name_en": "Other intangible assets", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "02",  "name_cz": "Dlouhodobý hmotný majetek odpisovaný", "name_en": "Depreciable tangible assets", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET", "is_synthetic": False, "allows_posting": False},
    {"account_number": "021", "name_cz": "Stavby", "name_en": "Buildings", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "022", "name_cz": "Hmotné movité věci a jejich soubory", "name_en": "Tangible movable assets", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "025", "name_cz": "Pěstitelské celky trvalých porostů", "name_en": "Perennial plant groups", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "026", "name_cz": "Dospělá zvířata a jejich skupiny", "name_en": "Mature animals", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "029", "name_cz": "Jiný dlouhodobý hmotný majetek", "name_en": "Other tangible assets", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "03",  "name_cz": "Dlouhodobý hmotný majetek neodpisovaný", "name_en": "Non-depreciable tangible assets", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET", "is_synthetic": False, "allows_posting": False},
    {"account_number": "031", "name_cz": "Pozemky", "name_en": "Land", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "032", "name_cz": "Umělecká díla a sbírky", "name_en": "Artworks and collections", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "04",  "name_cz": "Nedokončený a pořizovaný dlouhodobý majetek", "name_en": "Assets under construction", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET", "is_synthetic": False, "allows_posting": False},
    {"account_number": "041", "name_cz": "Nedokončený dlouhodobý nehmotný majetek", "name_en": "Intangible assets under construction", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "042", "name_cz": "Nedokončený dlouhodobý hmotný majetek", "name_en": "Tangible assets under construction", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "043", "name_cz": "Pořizovaný dlouhodobý finanční majetek", "name_en": "Financial assets being acquired", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "05",  "name_cz": "Poskytnuté zálohy na dlouhodobý majetek", "name_en": "Advances for fixed assets", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET", "is_synthetic": False, "allows_posting": False},
    {"account_number": "051", "name_cz": "Poskytnuté zálohy na dlouhodobý nehmotný majetek", "name_en": "Advances for intangibles", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "052", "name_cz": "Poskytnuté zálohy na dlouhodobý hmotný majetek", "name_en": "Advances for tangibles", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "053", "name_cz": "Poskytnuté zálohy na dlouhodobý finanční majetek", "name_en": "Advances for financial assets", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "06",  "name_cz": "Dlouhodobý finanční majetek", "name_en": "Long-term financial assets", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET", "is_synthetic": False, "allows_posting": False},
    {"account_number": "061", "name_cz": "Podíly — ovládaná nebo ovládající osoba", "name_en": "Shares — controlled entity", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "062", "name_cz": "Podíly — podstatný vliv", "name_en": "Shares — significant influence", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "063", "name_cz": "Ostatní dlouhodobé cenné papíry a podíly", "name_en": "Other long-term securities", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "065", "name_cz": "Dluhové cenné papíry držené do splatnosti", "name_en": "Debt securities held to maturity", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "066", "name_cz": "Půjčky a úvěry — ovládaná nebo ovládající osoba", "name_en": "Loans — group companies", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "067", "name_cz": "Půjčky a úvěry — podstatný vliv", "name_en": "Loans — associates", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "069", "name_cz": "Jiný dlouhodobý finanční majetek", "name_en": "Other long-term financial assets", "account_class": 0, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "07",  "name_cz": "Oprávky k dlouhodobému nehmotnému majetku", "name_en": "Accumulated amortisation — intangibles", "account_class": 0, "balance_type": "CREDIT", "account_type": "ASSET", "is_synthetic": False, "allows_posting": False},
    {"account_number": "071", "name_cz": "Oprávky ke zřizovacím výdajům", "name_en": "Acc. amortisation — formation expenses", "account_class": 0, "balance_type": "CREDIT", "account_type": "ASSET"},
    {"account_number": "072", "name_cz": "Oprávky k nehmotným výsledkům výzkumu a vývoje", "name_en": "Acc. amortisation — R&D", "account_class": 0, "balance_type": "CREDIT", "account_type": "ASSET"},
    {"account_number": "073", "name_cz": "Oprávky k softwaru", "name_en": "Acc. amortisation — software", "account_class": 0, "balance_type": "CREDIT", "account_type": "ASSET"},
    {"account_number": "074", "name_cz": "Oprávky k ocenitelným právům", "name_en": "Acc. amortisation — rights", "account_class": 0, "balance_type": "CREDIT", "account_type": "ASSET"},
    {"account_number": "075", "name_cz": "Oprávky ke goodwillu", "name_en": "Acc. amortisation — goodwill", "account_class": 0, "balance_type": "CREDIT", "account_type": "ASSET"},
    {"account_number": "079", "name_cz": "Oprávky k jinému dlouhodobému nehmotnému majetku", "name_en": "Acc. amortisation — other intangibles", "account_class": 0, "balance_type": "CREDIT", "account_type": "ASSET"},
    {"account_number": "08",  "name_cz": "Oprávky k dlouhodobému hmotnému majetku", "name_en": "Accumulated depreciation — tangibles", "account_class": 0, "balance_type": "CREDIT", "account_type": "ASSET", "is_synthetic": False, "allows_posting": False},
    {"account_number": "081", "name_cz": "Oprávky ke stavbám", "name_en": "Acc. depreciation — buildings", "account_class": 0, "balance_type": "CREDIT", "account_type": "ASSET"},
    {"account_number": "082", "name_cz": "Oprávky k hmotným movitým věcem", "name_en": "Acc. depreciation — movable assets", "account_class": 0, "balance_type": "CREDIT", "account_type": "ASSET"},
    {"account_number": "085", "name_cz": "Oprávky k pěstitelským celkům trvalých porostů", "name_en": "Acc. depreciation — perennial plants", "account_class": 0, "balance_type": "CREDIT", "account_type": "ASSET"},
    {"account_number": "086", "name_cz": "Oprávky k dospělým zvířatům", "name_en": "Acc. depreciation — mature animals", "account_class": 0, "balance_type": "CREDIT", "account_type": "ASSET"},
    {"account_number": "089", "name_cz": "Oprávky k jinému dlouhodobému hmotnému majetku", "name_en": "Acc. depreciation — other tangibles", "account_class": 0, "balance_type": "CREDIT", "account_type": "ASSET"},
    {"account_number": "09",  "name_cz": "Opravné položky k dlouhodobému majetku", "name_en": "Impairment allowances — fixed assets", "account_class": 0, "balance_type": "CREDIT", "account_type": "ASSET", "is_synthetic": False, "allows_posting": False},
    {"account_number": "091", "name_cz": "Opravná položka k dlouhodobému nehmotnému majetku", "name_en": "Impairment — intangibles", "account_class": 0, "balance_type": "CREDIT", "account_type": "ASSET"},
    {"account_number": "092", "name_cz": "Opravná položka k dlouhodobému hmotnému majetku", "name_en": "Impairment — tangibles", "account_class": 0, "balance_type": "CREDIT", "account_type": "ASSET"},
    {"account_number": "093", "name_cz": "Opravná položka k dlouhodobému nedokončenému majetku", "name_en": "Impairment — assets under construction", "account_class": 0, "balance_type": "CREDIT", "account_type": "ASSET"},
    {"account_number": "094", "name_cz": "Opravná položka k pořizovanému dlouhodobému majetku", "name_en": "Impairment — assets being acquired", "account_class": 0, "balance_type": "CREDIT", "account_type": "ASSET"},
    {"account_number": "095", "name_cz": "Opravná položka k poskytnutým zálohám", "name_en": "Impairment — advances paid", "account_class": 0, "balance_type": "CREDIT", "account_type": "ASSET"},
    {"account_number": "096", "name_cz": "Opravná položka k dlouhodobému finančnímu majetku", "name_en": "Impairment — financial assets", "account_class": 0, "balance_type": "CREDIT", "account_type": "ASSET"},

    # ─────────────────────────────────────────────────────────────
    # CLASS 1 — ZÁSOBY (Inventory)
    # ─────────────────────────────────────────────────────────────
    {"account_number": "11",  "name_cz": "Materiál", "name_en": "Materials", "account_class": 1, "balance_type": "DEBIT", "account_type": "ASSET", "is_synthetic": False, "allows_posting": False},
    {"account_number": "111", "name_cz": "Pořízení materiálu", "name_en": "Materials in transit", "account_class": 1, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "112", "name_cz": "Materiál na skladě", "name_en": "Materials in stock", "account_class": 1, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "119", "name_cz": "Materiál na cestě", "name_en": "Materials in transit (pipeline)", "account_class": 1, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "12",  "name_cz": "Zásoby vlastní výroby", "name_en": "Own production inventory", "account_class": 1, "balance_type": "DEBIT", "account_type": "ASSET", "is_synthetic": False, "allows_posting": False},
    {"account_number": "121", "name_cz": "Nedokončená výroba", "name_en": "Work in progress", "account_class": 1, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "122", "name_cz": "Polotovary vlastní výroby", "name_en": "Semi-finished own production", "account_class": 1, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "123", "name_cz": "Výrobky", "name_en": "Finished goods", "account_class": 1, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "124", "name_cz": "Mladá a ostatní zvířata a jejich skupiny", "name_en": "Young animals", "account_class": 1, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "13",  "name_cz": "Zboží", "name_en": "Goods for resale", "account_class": 1, "balance_type": "DEBIT", "account_type": "ASSET", "is_synthetic": False, "allows_posting": False},
    {"account_number": "131", "name_cz": "Pořízení zboží", "name_en": "Goods in transit", "account_class": 1, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "132", "name_cz": "Zboží na skladě a v prodejnách", "name_en": "Goods in stock", "account_class": 1, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "139", "name_cz": "Zboží na cestě", "name_en": "Goods in transit (pipeline)", "account_class": 1, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "19",  "name_cz": "Opravné položky k zásobám", "name_en": "Inventory impairment", "account_class": 1, "balance_type": "CREDIT", "account_type": "ASSET", "is_synthetic": False, "allows_posting": False},
    {"account_number": "191", "name_cz": "Opravná položka k materiálu", "name_en": "Impairment — materials", "account_class": 1, "balance_type": "CREDIT", "account_type": "ASSET"},
    {"account_number": "192", "name_cz": "Opravná položka k nedokončené výrobě", "name_en": "Impairment — WIP", "account_class": 1, "balance_type": "CREDIT", "account_type": "ASSET"},
    {"account_number": "193", "name_cz": "Opravná položka k polotovarům vlastní výroby", "name_en": "Impairment — semi-finished", "account_class": 1, "balance_type": "CREDIT", "account_type": "ASSET"},
    {"account_number": "194", "name_cz": "Opravná položka k výrobkům", "name_en": "Impairment — finished goods", "account_class": 1, "balance_type": "CREDIT", "account_type": "ASSET"},
    {"account_number": "195", "name_cz": "Opravná položka ke zvířatům", "name_en": "Impairment — animals", "account_class": 1, "balance_type": "CREDIT", "account_type": "ASSET"},
    {"account_number": "196", "name_cz": "Opravná položka ke zboží", "name_en": "Impairment — goods", "account_class": 1, "balance_type": "CREDIT", "account_type": "ASSET"},
    {"account_number": "197", "name_cz": "Opravná položka k zálohám na zásoby", "name_en": "Impairment — advances on inventory", "account_class": 1, "balance_type": "CREDIT", "account_type": "ASSET"},

    # ─────────────────────────────────────────────────────────────
    # CLASS 2 — KRÁTKODOBÝ FINANČNÍ MAJETEK A PENĚŽNÍ PROSTŘEDKY
    # (Cash, bank, short-term financial assets)
    # ─────────────────────────────────────────────────────────────
    {"account_number": "21",  "name_cz": "Peněžní prostředky v pokladně", "name_en": "Cash on hand", "account_class": 2, "balance_type": "DEBIT", "account_type": "ASSET", "is_synthetic": False, "allows_posting": False},
    {"account_number": "211", "name_cz": "Pokladna CZK", "name_en": "Cash register CZK", "account_class": 2, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "213", "name_cz": "Ceniny", "name_en": "Stamps and vouchers", "account_class": 2, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "22",  "name_cz": "Peněžní prostředky na účtech", "name_en": "Bank accounts", "account_class": 2, "balance_type": "DEBIT", "account_type": "ASSET", "is_synthetic": False, "allows_posting": False},
    {"account_number": "221", "name_cz": "Bankovní účty CZK", "name_en": "Bank account CZK", "account_class": 2, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "222", "name_cz": "Bankovní účty EUR", "name_en": "Bank account EUR", "account_class": 2, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "223", "name_cz": "Bankovní účty USD", "name_en": "Bank account USD", "account_class": 2, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "23",  "name_cz": "Krátkodobé úvěry", "name_en": "Short-term bank loans", "account_class": 2, "balance_type": "CREDIT", "account_type": "LIABILITY", "is_synthetic": False, "allows_posting": False},
    {"account_number": "231", "name_cz": "Krátkodobé bankovní úvěry", "name_en": "Short-term bank loans", "account_class": 2, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "232", "name_cz": "Eskontní úvěry", "name_en": "Bill discounting credit", "account_class": 2, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "24",  "name_cz": "Krátkodobé finanční výpomoci", "name_en": "Short-term financial assistance", "account_class": 2, "balance_type": "CREDIT", "account_type": "LIABILITY", "is_synthetic": False, "allows_posting": False},
    {"account_number": "241", "name_cz": "Vydané krátkodobé dluhopisy", "name_en": "Short-term bonds issued", "account_class": 2, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "249", "name_cz": "Ostatní krátkodobé finanční výpomoci", "name_en": "Other short-term financial assistance", "account_class": 2, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "25",  "name_cz": "Krátkodobý finanční majetek", "name_en": "Short-term financial assets", "account_class": 2, "balance_type": "DEBIT", "account_type": "ASSET", "is_synthetic": False, "allows_posting": False},
    {"account_number": "251", "name_cz": "Majetkové cenné papíry k obchodování", "name_en": "Equity securities for trading", "account_class": 2, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "253", "name_cz": "Dluhové cenné papíry k obchodování", "name_en": "Debt securities for trading", "account_class": 2, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "255", "name_cz": "Vlastní akcie a vlastní obchodní podíly", "name_en": "Treasury shares", "account_class": 2, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "256", "name_cz": "Dluhové cenné papíry se splatností do 1 roku", "name_en": "Debt securities < 1 year maturity", "account_class": 2, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "259", "name_cz": "Pořizovaný krátkodobý finanční majetek", "name_en": "Short-term financial assets being acquired", "account_class": 2, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "26",  "name_cz": "Převody mezi finančními účty", "name_en": "Transfers between financial accounts", "account_class": 2, "balance_type": "DEBIT", "account_type": "CLEARING", "is_synthetic": False, "allows_posting": False},
    {"account_number": "261", "name_cz": "Pokladna — peníze na cestě", "name_en": "Money in transit", "account_class": 2, "balance_type": "DEBIT", "account_type": "CLEARING"},
    {"account_number": "29",  "name_cz": "Opravné položky ke krátkodobému finančnímu majetku", "name_en": "Impairment — short-term financial assets", "account_class": 2, "balance_type": "CREDIT", "account_type": "ASSET", "is_synthetic": False, "allows_posting": False},
    {"account_number": "291", "name_cz": "Opravná položka ke krátkodobému finančnímu majetku", "name_en": "Impairment — short-term financial assets", "account_class": 2, "balance_type": "CREDIT", "account_type": "ASSET"},

    # ─────────────────────────────────────────────────────────────
    # CLASS 3 — ZÚČTOVACÍ VZTAHY (Receivables, Payables, Clearing)
    # This class is critical for Czech DPH compliance
    # ─────────────────────────────────────────────────────────────
    {"account_number": "31",  "name_cz": "Pohledávky", "name_en": "Receivables", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET", "is_synthetic": False, "allows_posting": False},
    {"account_number": "311", "name_cz": "Pohledávky z obchodních vztahů", "name_en": "Trade receivables", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "312", "name_cz": "Směnky k inkasu", "name_en": "Bills receivable", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "313", "name_cz": "Pohledávky za eskontované cenné papíry", "name_en": "Receivables from discounted securities", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "314", "name_cz": "Poskytnuté zálohy — dlouhodobé a krátkodobé", "name_en": "Advances paid", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "315", "name_cz": "Ostatní pohledávky", "name_en": "Other receivables", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "32",  "name_cz": "Závazky", "name_en": "Payables", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY", "is_synthetic": False, "allows_posting": False},
    {"account_number": "321", "name_cz": "Závazky z obchodních vztahů", "name_en": "Trade payables", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "322", "name_cz": "Směnky k úhradě", "name_en": "Bills payable", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "324", "name_cz": "Přijaté zálohy", "name_en": "Advances received", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "325", "name_cz": "Ostatní závazky", "name_en": "Other payables", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "33",  "name_cz": "Zúčtování se zaměstnanci a institucemi", "name_en": "Employee and institution settlements", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY", "is_synthetic": False, "allows_posting": False},
    {"account_number": "331", "name_cz": "Zaměstnanci — mzdy", "name_en": "Employee wages payable", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "333", "name_cz": "Ostatní závazky vůči zaměstnancům", "name_en": "Other employee liabilities", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "335", "name_cz": "Pohledávky za zaměstnanci", "name_en": "Receivables from employees", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "336", "name_cz": "Zúčtování s institucemi sociálního zabezpečení a zdravotního pojištění", "name_en": "Social security and health insurance", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "34",  "name_cz": "Zúčtování daní a dotací", "name_en": "Tax and subsidy settlements", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY", "is_synthetic": False, "allows_posting": False},
    {"account_number": "341", "name_cz": "Daň z příjmů", "name_en": "Income tax payable", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "342", "name_cz": "Ostatní přímé daně", "name_en": "Other direct taxes", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "343", "name_cz": "Daň z přidané hodnoty", "name_en": "VAT payable/receivable", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY", "is_vat_account": True},
    {"account_number": "345", "name_cz": "Ostatní daně a poplatky", "name_en": "Other taxes and fees", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "346", "name_cz": "Dotace ze státního rozpočtu", "name_en": "State budget subsidies", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "347", "name_cz": "Ostatní dotace", "name_en": "Other subsidies", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "35",  "name_cz": "Pohledávky za společníky", "name_en": "Receivables from shareholders", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET", "is_synthetic": False, "allows_posting": False},
    {"account_number": "351", "name_cz": "Pohledávky za ovládanými osobami", "name_en": "Receivables — subsidiaries", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "352", "name_cz": "Pohledávky za osobami s podstatným vlivem", "name_en": "Receivables — associates", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "353", "name_cz": "Pohledávky za upsaný vlastní kapitál", "name_en": "Receivables — subscribed capital", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "354", "name_cz": "Pohledávky za společníky při úhradě ztráty", "name_en": "Receivables — loss funding", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "355", "name_cz": "Ostatní pohledávky za společníky", "name_en": "Other receivables — shareholders", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "358", "name_cz": "Pohledávky za společníky sdružení", "name_en": "Receivables — partners in association", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "36",  "name_cz": "Závazky ke společníkům", "name_en": "Payables to shareholders", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY", "is_synthetic": False, "allows_posting": False},
    {"account_number": "361", "name_cz": "Závazky k ovládaným osobám", "name_en": "Payables — subsidiaries", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "362", "name_cz": "Závazky k osobám s podstatným vlivem", "name_en": "Payables — associates", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "364", "name_cz": "Závazky ke společníkům při rozdělení zisku", "name_en": "Payables — profit distribution", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "365", "name_cz": "Ostatní závazky ke společníkům", "name_en": "Other payables — shareholders", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "366", "name_cz": "Závazky ke společníkům sdružení", "name_en": "Payables — partners in association", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "37",  "name_cz": "Jiné pohledávky a závazky", "name_en": "Other receivables and payables", "account_class": 3, "balance_type": "DEBIT", "account_type": "CLEARING", "is_synthetic": False, "allows_posting": False},
    {"account_number": "371", "name_cz": "Pohledávky z prodeje podniku", "name_en": "Receivables from business sale", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "372", "name_cz": "Závazky z koupě podniku", "name_en": "Payables from business purchase", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "373", "name_cz": "Pohledávky a závazky z pevných termínových operací", "name_en": "Forward contract assets/liabilities", "account_class": 3, "balance_type": "DEBIT", "account_type": "CLEARING"},
    {"account_number": "374", "name_cz": "Pohledávky z pronájmu", "name_en": "Rental receivables", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "375", "name_cz": "Pohledávky z emitovaných dluhopisů", "name_en": "Receivables from bonds issued", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "376", "name_cz": "Nakoupené opce", "name_en": "Purchased options", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "377", "name_cz": "Prodané opce", "name_en": "Written options", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "378", "name_cz": "Jiné pohledávky", "name_en": "Other sundry receivables", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "379", "name_cz": "Jiné závazky", "name_en": "Other sundry payables", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "38",  "name_cz": "Přechodné účty aktiv a pasiv", "name_en": "Accruals and deferrals", "account_class": 3, "balance_type": "DEBIT", "account_type": "CLEARING", "is_synthetic": False, "allows_posting": False},
    {"account_number": "381", "name_cz": "Náklady příštích období", "name_en": "Prepaid expenses", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "382", "name_cz": "Komplexní náklady příštích období", "name_en": "Complex deferred expenses", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "383", "name_cz": "Výdaje příštích období", "name_en": "Accrued expenses", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "384", "name_cz": "Výnosy příštích období", "name_en": "Deferred income", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "385", "name_cz": "Příjmy příštích období", "name_en": "Accrued income", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "388", "name_cz": "Dohadné účty aktivní", "name_en": "Estimated receivables", "account_class": 3, "balance_type": "DEBIT", "account_type": "ASSET"},
    {"account_number": "389", "name_cz": "Dohadné účty pasivní", "name_en": "Estimated payables", "account_class": 3, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "39",  "name_cz": "Opravná položka k zúčtovacím vztahům a vnitřní zúčtování", "name_en": "Impairment and intercompany clearing", "account_class": 3, "balance_type": "CREDIT", "account_type": "CLEARING", "is_synthetic": False, "allows_posting": False},
    {"account_number": "391", "name_cz": "Opravná položka k pohledávkám", "name_en": "Impairment — receivables", "account_class": 3, "balance_type": "CREDIT", "account_type": "ASSET"},
    {"account_number": "395", "name_cz": "Vnitřní zúčtování", "name_en": "Intercompany clearing", "account_class": 3, "balance_type": "DEBIT", "account_type": "CLEARING"},
    {"account_number": "398", "name_cz": "Spojovací účet při sdružení", "name_en": "Pooling account", "account_class": 3, "balance_type": "DEBIT", "account_type": "CLEARING"},

    # ─────────────────────────────────────────────────────────────
    # CLASS 4 — KAPITÁLOVÉ ÚČTY A DLOUHODOBÉ ZÁVAZKY
    # (Equity & Long-term Liabilities)
    # ─────────────────────────────────────────────────────────────
    {"account_number": "41",  "name_cz": "Základní kapitál a kapitálové fondy", "name_en": "Share capital and capital funds", "account_class": 4, "balance_type": "CREDIT", "account_type": "EQUITY", "is_synthetic": False, "allows_posting": False},
    {"account_number": "411", "name_cz": "Základní kapitál", "name_en": "Share capital", "account_class": 4, "balance_type": "CREDIT", "account_type": "EQUITY"},
    {"account_number": "412", "name_cz": "Emisní ážio", "name_en": "Share premium", "account_class": 4, "balance_type": "CREDIT", "account_type": "EQUITY"},
    {"account_number": "413", "name_cz": "Ostatní kapitálové fondy", "name_en": "Other capital funds", "account_class": 4, "balance_type": "CREDIT", "account_type": "EQUITY"},
    {"account_number": "414", "name_cz": "Oceňovací rozdíly z přecenění majetku a závazků", "name_en": "Revaluation surplus", "account_class": 4, "balance_type": "CREDIT", "account_type": "EQUITY"},
    {"account_number": "418", "name_cz": "Oceňovací rozdíly z přecenění při přeměnách", "name_en": "Revaluation — reorganisations", "account_class": 4, "balance_type": "CREDIT", "account_type": "EQUITY"},
    {"account_number": "419", "name_cz": "Změny základního kapitálu", "name_en": "Changes in share capital", "account_class": 4, "balance_type": "CREDIT", "account_type": "EQUITY"},
    {"account_number": "42",  "name_cz": "Fondy ze zisku a převedené výsledky hospodaření", "name_en": "Profit reserves and retained earnings", "account_class": 4, "balance_type": "CREDIT", "account_type": "EQUITY", "is_synthetic": False, "allows_posting": False},
    {"account_number": "421", "name_cz": "Rezervní fond", "name_en": "Legal reserve fund", "account_class": 4, "balance_type": "CREDIT", "account_type": "EQUITY"},
    {"account_number": "422", "name_cz": "Nedělitelný fond", "name_en": "Indivisible fund (cooperative)", "account_class": 4, "balance_type": "CREDIT", "account_type": "EQUITY"},
    {"account_number": "423", "name_cz": "Statutární fondy", "name_en": "Statutory funds", "account_class": 4, "balance_type": "CREDIT", "account_type": "EQUITY"},
    {"account_number": "427", "name_cz": "Ostatní fondy", "name_en": "Other funds", "account_class": 4, "balance_type": "CREDIT", "account_type": "EQUITY"},
    {"account_number": "428", "name_cz": "Nerozdělený zisk minulých let", "name_en": "Retained earnings", "account_class": 4, "balance_type": "CREDIT", "account_type": "EQUITY"},
    {"account_number": "429", "name_cz": "Neuhrazená ztráta minulých let", "name_en": "Accumulated losses", "account_class": 4, "balance_type": "DEBIT", "account_type": "EQUITY"},
    {"account_number": "43",  "name_cz": "Výsledek hospodaření", "name_en": "Current year profit/loss", "account_class": 4, "balance_type": "CREDIT", "account_type": "EQUITY", "is_synthetic": False, "allows_posting": False},
    {"account_number": "431", "name_cz": "Výsledek hospodaření ve schvalovacím řízení", "name_en": "Profit/loss pending approval", "account_class": 4, "balance_type": "CREDIT", "account_type": "EQUITY"},
    {"account_number": "45",  "name_cz": "Rezervy", "name_en": "Provisions", "account_class": 4, "balance_type": "CREDIT", "account_type": "LIABILITY", "is_synthetic": False, "allows_posting": False},
    {"account_number": "451", "name_cz": "Rezervy podle zvláštních právních předpisů", "name_en": "Statutory provisions", "account_class": 4, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "453", "name_cz": "Rezerva na daň z příjmů", "name_en": "Income tax provision", "account_class": 4, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "459", "name_cz": "Ostatní rezervy", "name_en": "Other provisions", "account_class": 4, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "46",  "name_cz": "Dlouhodobé bankovní úvěry", "name_en": "Long-term bank loans", "account_class": 4, "balance_type": "CREDIT", "account_type": "LIABILITY", "is_synthetic": False, "allows_posting": False},
    {"account_number": "461", "name_cz": "Dlouhodobé bankovní úvěry", "name_en": "Long-term bank loans", "account_class": 4, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "47",  "name_cz": "Dlouhodobé závazky", "name_en": "Long-term payables", "account_class": 4, "balance_type": "CREDIT", "account_type": "LIABILITY", "is_synthetic": False, "allows_posting": False},
    {"account_number": "471", "name_cz": "Dlouhodobé závazky — ovládaná nebo ovládající osoba", "name_en": "LT payables — group", "account_class": 4, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "472", "name_cz": "Dlouhodobé závazky — podstatný vliv", "name_en": "LT payables — associates", "account_class": 4, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "473", "name_cz": "Emitované dluhopisy", "name_en": "Bonds issued", "account_class": 4, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "474", "name_cz": "Závazky z pronájmu", "name_en": "Lease liabilities", "account_class": 4, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "475", "name_cz": "Dlouhodobé přijaté zálohy", "name_en": "Long-term advances received", "account_class": 4, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "478", "name_cz": "Dlouhodobé směnky k úhradě", "name_en": "Long-term bills payable", "account_class": 4, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "479", "name_cz": "Ostatní dlouhodobé závazky", "name_en": "Other long-term payables", "account_class": 4, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "48",  "name_cz": "Odložený daňový závazek a pohledávka", "name_en": "Deferred tax", "account_class": 4, "balance_type": "CREDIT", "account_type": "LIABILITY", "is_synthetic": False, "allows_posting": False},
    {"account_number": "481", "name_cz": "Odložený daňový závazek a pohledávka", "name_en": "Deferred tax liability/asset", "account_class": 4, "balance_type": "CREDIT", "account_type": "LIABILITY"},
    {"account_number": "49",  "name_cz": "Individuální podnikatel", "name_en": "Sole trader capital", "account_class": 4, "balance_type": "CREDIT", "account_type": "EQUITY", "is_synthetic": False, "allows_posting": False},
    {"account_number": "491", "name_cz": "Účet individuálního podnikatele", "name_en": "Sole trader account", "account_class": 4, "balance_type": "CREDIT", "account_type": "EQUITY"},

    # ─────────────────────────────────────────────────────────────
    # CLASS 5 — NÁKLADY (Expenses)
    # ─────────────────────────────────────────────────────────────
    {"account_number": "50",  "name_cz": "Spotřebované nákupy", "name_en": "Consumed purchases", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE", "is_synthetic": False, "allows_posting": False},
    {"account_number": "501", "name_cz": "Spotřeba materiálu", "name_en": "Materials consumed", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "502", "name_cz": "Spotřeba energie", "name_en": "Energy consumed", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "503", "name_cz": "Spotřeba ostatních neskladovatelných dodávek", "name_en": "Other non-storable supplies", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "504", "name_cz": "Prodané zboží", "name_en": "Cost of goods sold", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "51",  "name_cz": "Služby", "name_en": "Services", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE", "is_synthetic": False, "allows_posting": False},
    {"account_number": "511", "name_cz": "Opravy a udržování", "name_en": "Repairs and maintenance", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "512", "name_cz": "Cestovné", "name_en": "Travel expenses", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "513", "name_cz": "Náklady na reprezentaci", "name_en": "Representation expenses", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE", "notes": "Non-deductible for DPPO per § 25 odst. 1 písm. t) ZDP"},
    {"account_number": "518", "name_cz": "Ostatní služby", "name_en": "Other services", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "52",  "name_cz": "Osobní náklady", "name_en": "Personnel costs", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE", "is_synthetic": False, "allows_posting": False},
    {"account_number": "521", "name_cz": "Mzdové náklady", "name_en": "Wages and salaries", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "522", "name_cz": "Příjmy společníků ze závislé činnosti", "name_en": "Partner employment income", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "523", "name_cz": "Odměny členům orgánů obchodní korporace", "name_en": "Board member fees", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "524", "name_cz": "Zákonné sociální pojištění", "name_en": "Statutory social insurance (employer)", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "525", "name_cz": "Ostatní sociální pojištění", "name_en": "Other social insurance", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "526", "name_cz": "Sociální náklady individuálního podnikatele", "name_en": "Sole trader social costs", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "527", "name_cz": "Zákonné sociální náklady", "name_en": "Statutory social benefits", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "528", "name_cz": "Ostatní sociální náklady", "name_en": "Other social costs", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "53",  "name_cz": "Daně a poplatky", "name_en": "Taxes and fees (expense)", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE", "is_synthetic": False, "allows_posting": False},
    {"account_number": "531", "name_cz": "Daň silniční", "name_en": "Road tax", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "532", "name_cz": "Daň z nemovitých věcí", "name_en": "Real estate tax", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "538", "name_cz": "Ostatní daně a poplatky", "name_en": "Other taxes and fees", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "54",  "name_cz": "Jiné provozní náklady", "name_en": "Other operating expenses", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE", "is_synthetic": False, "allows_posting": False},
    {"account_number": "541", "name_cz": "Zůstatková cena prodaného DHM a DNM", "name_en": "Net book value — disposed assets", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "542", "name_cz": "Prodaný materiál", "name_en": "Materials sold", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "543", "name_cz": "Dary", "name_en": "Gifts (non-deductible)", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE", "notes": "Non-deductible for DPPO — § 25 odst. 1 písm. t) ZDP"},
    {"account_number": "544", "name_cz": "Smluvní pokuty a úroky z prodlení", "name_en": "Contractual penalties and late interest", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "545", "name_cz": "Ostatní pokuty a penále", "name_en": "Other fines and penalties", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE", "notes": "Tax authority penalties are non-deductible"},
    {"account_number": "546", "name_cz": "Odpis pohledávky", "name_en": "Write-off of receivables", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "548", "name_cz": "Ostatní provozní náklady", "name_en": "Other operating costs", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "549", "name_cz": "Manka a škody z provozní činnosti", "name_en": "Shortages and losses", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "55",  "name_cz": "Odpisy, rezervy, komplexní náklady příštích období a opravné položky v provozní oblasti", "name_en": "Depreciation, provisions and impairment", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE", "is_synthetic": False, "allows_posting": False},
    {"account_number": "551", "name_cz": "Odpisy dlouhodobého nehmotného a hmotného majetku", "name_en": "Depreciation — intangible and tangible", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "552", "name_cz": "Tvorba a zúčtování rezerv podle zvláštních předpisů", "name_en": "Statutory provisions movement", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "554", "name_cz": "Tvorba a zúčtování ostatních rezerv", "name_en": "Other provisions movement", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "555", "name_cz": "Tvorba a zúčtování komplexních nákladů příštích období", "name_en": "Deferred complex costs movement", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "557", "name_cz": "Zúčtování oprávky k záporné hodnotě goodwillu", "name_en": "Negative goodwill amortisation", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "558", "name_cz": "Tvorba a zúčtování zákonných opravných položek v provozní oblasti", "name_en": "Statutory impairment — operating", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "559", "name_cz": "Tvorba a zúčtování opravných položek v provozní oblasti", "name_en": "Impairment movement — operating", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "56",  "name_cz": "Finanční náklady", "name_en": "Financial expenses", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE", "is_synthetic": False, "allows_posting": False},
    {"account_number": "561", "name_cz": "Prodané cenné papíry a podíly", "name_en": "Securities and shares sold — cost", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "562", "name_cz": "Úroky", "name_en": "Interest expense", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "563", "name_cz": "Kurzové ztráty", "name_en": "Foreign exchange losses", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "564", "name_cz": "Náklady z přecenění cenných papírů", "name_en": "Securities revaluation losses", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "566", "name_cz": "Náklady z finančního majetku", "name_en": "Costs from financial assets", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "567", "name_cz": "Náklady z derivátových operací", "name_en": "Derivative losses", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "568", "name_cz": "Ostatní finanční náklady", "name_en": "Other financial expenses", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "569", "name_cz": "Manka a škody na finančním majetku", "name_en": "Financial asset shortages", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "57",  "name_cz": "Rezervy a opravné položky finančních nákladů", "name_en": "Financial provisions and impairment", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE", "is_synthetic": False, "allows_posting": False},
    {"account_number": "574", "name_cz": "Tvorba a zúčtování finančních rezerv", "name_en": "Financial provisions movement", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "579", "name_cz": "Tvorba a zúčtování opravných položek ve finanční oblasti", "name_en": "Financial impairment movement", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "58",  "name_cz": "Změna stavu zásob vlastní činnosti a aktivace", "name_en": "Inventory changes and capitalisation", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE", "is_synthetic": False, "allows_posting": False},
    {"account_number": "581", "name_cz": "Změna stavu nedokončené výroby", "name_en": "WIP inventory change", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "582", "name_cz": "Změna stavu polotovarů", "name_en": "Semi-finished goods inventory change", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "583", "name_cz": "Změna stavu výrobků", "name_en": "Finished goods inventory change", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "584", "name_cz": "Změna stavu zvířat", "name_en": "Animals inventory change", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "585", "name_cz": "Aktivace materiálu a zboží", "name_en": "Capitalisation — materials", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "586", "name_cz": "Aktivace vnitropodnikových služeb", "name_en": "Capitalisation — internal services", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "587", "name_cz": "Aktivace dlouhodobého nehmotného majetku", "name_en": "Capitalisation — intangibles", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "588", "name_cz": "Aktivace dlouhodobého hmotného majetku", "name_en": "Capitalisation — tangibles", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "59",  "name_cz": "Daně z příjmů a převodové účty", "name_en": "Income taxes and transfer accounts", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE", "is_synthetic": False, "allows_posting": False},
    {"account_number": "591", "name_cz": "Daň z příjmů — splatná", "name_en": "Current income tax", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "592", "name_cz": "Daň z příjmů z mimořádné činnosti — splatná", "name_en": "Income tax — extraordinary (current)", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "593", "name_cz": "Daň z příjmů — odložená", "name_en": "Deferred income tax", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "595", "name_cz": "Dodatečné odvody daně z příjmů", "name_en": "Additional income tax charges", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "596", "name_cz": "Převod podílu na výsledku hospodaření společníkům", "name_en": "Profit distribution to partners", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "597", "name_cz": "Převod provozních nákladů", "name_en": "Transfer of operating costs", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},
    {"account_number": "598", "name_cz": "Převod finančních nákladů", "name_en": "Transfer of financial costs", "account_class": 5, "balance_type": "DEBIT", "account_type": "EXPENSE"},

    # ─────────────────────────────────────────────────────────────
    # CLASS 6 — VÝNOSY (Revenue)
    # ─────────────────────────────────────────────────────────────
    {"account_number": "60",  "name_cz": "Tržby za výkony a zboží", "name_en": "Revenue from output and goods", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE", "is_synthetic": False, "allows_posting": False},
    {"account_number": "601", "name_cz": "Tržby za vlastní výrobky", "name_en": "Revenue — own products", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "602", "name_cz": "Tržby z prodeje služeb", "name_en": "Revenue — services", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "604", "name_cz": "Tržby za zboží", "name_en": "Revenue — goods sold", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "61",  "name_cz": "Změny stavu zásob vlastní činnosti", "name_en": "Inventory changes (own production)", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE", "is_synthetic": False, "allows_posting": False},
    {"account_number": "611", "name_cz": "Změna stavu nedokončené výroby", "name_en": "WIP change", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "612", "name_cz": "Změna stavu polotovarů vlastní výroby", "name_en": "Semi-finished goods change", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "613", "name_cz": "Změna stavu výrobků", "name_en": "Finished goods change", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "614", "name_cz": "Změna stavu zvířat", "name_en": "Animals change", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "62",  "name_cz": "Aktivace", "name_en": "Capitalisation (income side)", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE", "is_synthetic": False, "allows_posting": False},
    {"account_number": "621", "name_cz": "Aktivace materiálu a zboží", "name_en": "Capitalisation — materials (income)", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "622", "name_cz": "Aktivace vnitropodnikových služeb", "name_en": "Capitalisation — services (income)", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "623", "name_cz": "Aktivace dlouhodobého nehmotného majetku", "name_en": "Capitalisation — intangibles (income)", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "624", "name_cz": "Aktivace dlouhodobého hmotného majetku", "name_en": "Capitalisation — tangibles (income)", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "64",  "name_cz": "Jiné provozní výnosy", "name_en": "Other operating income", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE", "is_synthetic": False, "allows_posting": False},
    {"account_number": "641", "name_cz": "Tržby z prodeje dlouhodobého nehmotného a hmotného majetku", "name_en": "Proceeds from asset disposal", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "642", "name_cz": "Tržby z prodeje materiálu", "name_en": "Proceeds from materials sold", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "644", "name_cz": "Smluvní pokuty a úroky z prodlení", "name_en": "Contractual penalties received", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "646", "name_cz": "Výnosy z odepsaných pohledávek", "name_en": "Income from written-off receivables", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "648", "name_cz": "Ostatní provozní výnosy", "name_en": "Other operating income misc.", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "66",  "name_cz": "Finanční výnosy", "name_en": "Financial income", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE", "is_synthetic": False, "allows_posting": False},
    {"account_number": "661", "name_cz": "Tržby z prodeje cenných papírů a podílů", "name_en": "Proceeds from securities sold", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "662", "name_cz": "Úroky", "name_en": "Interest income", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "663", "name_cz": "Kurzové zisky", "name_en": "Foreign exchange gains", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "664", "name_cz": "Výnosy z přecenění cenných papírů", "name_en": "Securities revaluation gains", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "665", "name_cz": "Výnosy z dlouhodobého finančního majetku", "name_en": "Income from long-term financial assets", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "666", "name_cz": "Výnosy z krátkodobého finančního majetku", "name_en": "Income from short-term financial assets", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "667", "name_cz": "Výnosy z derivátových operací", "name_en": "Derivative income", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "668", "name_cz": "Ostatní finanční výnosy", "name_en": "Other financial income", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "69",  "name_cz": "Převodové účty", "name_en": "Transfer accounts", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE", "is_synthetic": False, "allows_posting": False},
    {"account_number": "697", "name_cz": "Převod provozních výnosů", "name_en": "Transfer of operating income", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},
    {"account_number": "698", "name_cz": "Převod finančních výnosů", "name_en": "Transfer of financial income", "account_class": 6, "balance_type": "CREDIT", "account_type": "REVENUE"},

    # ─────────────────────────────────────────────────────────────
    # CLASS 7 — ZÁVĚRKOVÉ A PODROZVAHOVÉ ÚČTY
    # (Closing accounts & off-balance sheet)
    # ─────────────────────────────────────────────────────────────
    {"account_number": "70",  "name_cz": "Účty rozvažné", "name_en": "Balance sheet closing accounts", "account_class": 7, "balance_type": "DEBIT", "account_type": "CLEARING", "is_synthetic": False, "allows_posting": False},
    {"account_number": "701", "name_cz": "Počáteční účet rozvažný", "name_en": "Opening balance sheet account", "account_class": 7, "balance_type": "DEBIT", "account_type": "CLEARING"},
    {"account_number": "702", "name_cz": "Konečný účet rozvažný", "name_en": "Closing balance sheet account", "account_class": 7, "balance_type": "DEBIT", "account_type": "CLEARING"},
    {"account_number": "71",  "name_cz": "Účet zisků a ztrát", "name_en": "Profit and loss account", "account_class": 7, "balance_type": "DEBIT", "account_type": "CLEARING", "is_synthetic": False, "allows_posting": False},
    {"account_number": "710", "name_cz": "Účet zisků a ztrát", "name_en": "Profit and loss closing account", "account_class": 7, "balance_type": "DEBIT", "account_type": "CLEARING"},
    {"account_number": "75",  "name_cz": "Podrozvahové účty — evidenční", "name_en": "Off-balance sheet memorandum accounts", "account_class": 7, "balance_type": "DEBIT", "account_type": "OFF_BALANCE", "is_synthetic": False, "allows_posting": False},
    {"account_number": "751", "name_cz": "Najatý majetek", "name_en": "Leased assets (operating lease)", "account_class": 7, "balance_type": "DEBIT", "account_type": "OFF_BALANCE"},
    {"account_number": "752", "name_cz": "Majetek přijatý do úschovy", "name_en": "Assets held in custody", "account_class": 7, "balance_type": "DEBIT", "account_type": "OFF_BALANCE"},
    {"account_number": "753", "name_cz": "Majetek přijatý k použití", "name_en": "Assets received for use", "account_class": 7, "balance_type": "DEBIT", "account_type": "OFF_BALANCE"},
    {"account_number": "758", "name_cz": "Ostatní podrozvahové účty", "name_en": "Other off-balance sheet items", "account_class": 7, "balance_type": "DEBIT", "account_type": "OFF_BALANCE"},
]

# Default field values — applied to every entry if not specified
DEFAULTS = {
    "is_synthetic": True,
    "is_analytical": False,
    "allows_posting": True,
    "is_vat_account": False,
    "vat_rate": None,
    "report_line_rozvaha": None,
    "report_line_vzz": None,
    "is_active": True,
    "notes": None,
    "name_en": None,
    "parent_account_number": None,
}

def get_full_chart():
    """Return the chart with all defaults applied."""
    result = []
    for entry in CHART_OF_ACCOUNTS:
        row = {**DEFAULTS, **entry}
        # Derive account_class from first digit of account_number if not set
        if "account_class" not in entry:
            row["account_class"] = int(entry["account_number"][0])
        result.append(row)
    return result
